### ISSUE TITLE
iOS simulator GetPurchasesAsync is not returning or giving an error

### ISSUE THREAD

**Issue by jaluka** [jamesmontemagno/InAppBillingPlugin#499]
On iOS simulator GetPurchasesAsync is not returning or giving an error

Version Number of Plugin: 5.6.1
Device Tested On: -
Simulator Tested On: iPhone 14 iOS 16
Version of VS: 17.3.5
Version of Xamarin: 5.0.0.2196
Versions of other things you are using:

### Steps to reproduce the Behavior
Create new Xamarin form project
Add version 5.6.1 of plugin
Follow getting stared section for iOS and Android
Add restore ButtonRestore and code from your test project
Click button

### Expected Behavior
GetPurchasesAsync will return

### Actual Behavior
GetPurchasesAsync  never returns

### Code snippet
        private async void ButtonRestore_Clicked(object sender, EventArgs e)
        {
            try
            {
                await CrossInAppBilling.Current.ConnectAsync();
                var purchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);

                if (purchases == null)
                {
                    await DisplayAlert(string.Empty, "Did not purchase", "OK");
                }
                else
                {
                    await DisplayAlert(string.Empty, "We did it!", "OK");
                }
            }
            catch (Exception ex)
            {

                Console.WriteLine(ex);
            }
            finally
            {

                await CrossInAppBilling.Current.DisconnectAsync();
            }
        }

### Sample project
[InAppTest.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/9672117/InAppTest.zip)

**Comment by VitalyKnyazev** [comment]
This seems to be related https://github.com/bizz84/SwiftyStoreKit/issues/682
I have the same issue since upgrading to iOS 16: existing production app works ok, any new build (even from TestFlight) hangs as restoreCompletedTransactions is never called.
Tried Xcode 14 and 13, have latest VS etc.

**Comment by jaluka** [comment]
After some more testing is seems to be an iOS 16 issues on real or the simulator.

The same code on IOSs 15.5 and 14.5 work as expected.

**Comment by phillippschmedt** [comment]
I can report that we have the same issue.

**Comment by phillippschmedt** [comment]
Do we have any news on this? Did anyone find a solution? This is a major issue.

**Comment by PaoloLeva** [comment]
this is a big issue for us as well. Backing to v4 at the moment

**Comment by Sebastian1989101** [comment]
@jamesmontemagno this issue is currently a release blocker. Any chance that this can be fixed soon?

**Comment by VitalyKnyazev** [comment]
Wow, just installed iOS 16.1 - now everything works just fine without any code change!

**Comment by phillippschmedt** [comment]
it looks like iOS 16.1 solved it for me too.

**Comment by jaluka** [comment]
https://developer.apple.com/documentation/ios-ipados-release-notes/ios-16_1-release-notes

StoreKit - Resolved Issues

Fixed an issue where restoring transactions wouldn’t prompt for authentication or restore any transactions if there was no App Store account signed in. (99506258)

Fixed an issue where purchasing or restoring in-app transactions with hosted content would block new purchases or restores from processing. (100117681)

**Comment by Sebastian1989101** [comment]
> https://developer.apple.com/documentation/ios-ipados-release-notes/ios-16_1-release-notes
> 
> StoreKit - Resolved Issues
> 
> Fixed an issue where restoring transactions wouldn’t prompt for authentication or restore any transactions if there was no App Store account signed in. (99506258)
> 
> Fixed an issue where purchasing or restoring in-app transactions with hosted content would block new purchases or restores from processing. (100117681)

Did you built your app again with the Xcode for iOS 16.1 or how did you solve this? Because my app still gets nothing back from the GetPurchasesAsync method and my devices runs on iOS 16.1. I just ask because Xcode is still on iOS 16.0 for the latest release version.

**Comment by rsbepvb** [comment]
Yes, updating to 16.1 fixed the issue.  Now have to determine what to do with users who are on 16.0 and haven't updated yet.

**Comment by Sebastian1989101** [comment]
> Yes, updating to 16.1 fixed the issue. Now have to determine what to do with users who are on 16.0 and haven't updated yet.

I run iOS 16.1 and still have this issue since I updated this library. Apps using Version 4.0.2 still works fine on iOS 16 and iOS 16.1. I assume it's more like a issue with the Xamarin.iOS then or the changes in this lib since 4.0.2.

**Comment by phillippschmedt** [comment]
> > Yes, updating to 16.1 fixed the issue. Now have to determine what to do with users who are on 16.0 and haven't updated yet.
> 
> I run iOS 16.1 and still have this issue since I updated this library. Apps using Version 4.0.2 still works fine on iOS 16 and iOS 16.1. I assume it's more like a issue with the Xamarin.iOS then or the changes in this lib since 4.0.2.

That's interesting. For me the error came with iOS 16 regardless of the version of InAppBilling and disappeared with iOS 16.1, again regardless of the version of InAppBilling.

**Comment by jaluka** [comment]
This has been fixed by Apple in the latest xcode 4.1, iOS 16.1 and Visual Studio 17.4
