### ISSUE TITLE
iOS 11 Error

### ISSUE THREAD

**Issue by cklenk** [jamesmontemagno/InAppBillingPlugin#79]
## Bug Information

Version Number of Plugin: 1.2.2
Device Tested On: iPhone 5s iOS 11
Simulator Tested On: N/A
Version of VS: 2017 Pro
Version of Xamarin: 4.6.3.4
Versions of other things you are using:
Xamarin.Forms: 2.3.4.270

### Steps to reproduce the Behavior
Just updated the phone to iOS 11. I then tried to make a call to PurchaseAsync with item Type of Subscription.

### Actual Behavior
Throws InAppBillingPurchaseException - cannot connect to iTunes store
### Code snippet
```
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <6314851f133e4e74a2e96356deaa0c6c>:0 
  at Plugin.InAppBilling.InAppBillingImplementation+<PurchaseAsync>d__11.MoveNext () [0x0002b] in C:\projects\inappbillingplugin\src\Plugin.InAppBilling.iOS\InAppBillingImplementation.cs:144 
```

**Comment by cklenk** [comment]
I have also noticed the sign into the iTunes store pop-up appears twice. I try to sign in with my sandbox account and right after I hit buy the same dialog opens again asking me to sign in. After I sign in the second time is when I get the cannot connect to iTunes store. And according to https://www.apple.com/support/systemstatus/ it all seems to be working.

**Comment by jamesmontemagno** [comment]
Please see: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

Works fine for me

**Comment by cklenk** [comment]
Okay thank you it seems to have been a firewall issue on my end.

**Comment by sinclas** [comment]
I keep getting the login pop-up.  When I hit cancel it will throw the exception Cannot connect to the iTunes store.  This was working fine in the sandbox and then I updated to iOS 11.  Seems to not be working anymore and the only change I made was the updated OS(11).  so I might be missing something new?

**Comment by cklenk** [comment]
Do you need to be using the AppStore build configuration when testing sandbox IAP?

**Comment by sinclas** [comment]
Hi,

Thanks for the reply.  After going through the check lists on how to resolve this, I found the issue this morning.  Somehow after the 11 update, iTunes Connect was showing that there was a bank field missing called Account Type.  This must have been recently added, since I have had the sandbox working for over two months!   When I fixed the error by logging into iTunes Connect, select the account type and waiting for about 5 hours, the sandbox user started working again.  Ugh!  note to self:  Check itunes connect FIRST, before debugging the tech!!

Thanks for the replies.  Problem resolved.

Steve

**Comment by cklenk** [comment]
@sinclas  where was Account Type missing?

Thanks

**Comment by sunkarikranthi** [comment]
**## Throws InAppBillingPurchaseException - cannot connect to iTunes store**
I tried for long time by updating packages changing code, but could not solved. Can you help me in this...

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
